### ISSUE TITLE
Oracle test starts failing (listener refused the connection)

### ISSUE THREAD

**Issue by javiertuya** [giis-uniovi/qacover#106]
Latest Combined dependency updates (2023-11-25) #100 ran successfully on main: https://github.com/giis-uniovi/qacover/actions/runs/6987984114, Suddenly some unrelated udpates of other components started failing the oracle job. After rerunning the above update, it failed too. It seems to be a problem with the docker image, memory resources, etc...

```
Error:  Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.054 s <<< FAILURE! -- in test4giis.qacover.oracle.TestOracleExecute
Error:  test4giis.qacover.oracle.TestOracleExecute.testExecuteUpdateNoParameters -- Time elapsed: 0.034 s <<< ERROR!
giis.qacover.portable.QaCoverException: Schema Exception
	at test4giis.qacoverapp.AppBase.executeUpdateNative(AppBase.java:59)
	at test4giis.qacover.TestExecute.setUpTestData(TestExecute.java:41)
	at test4giis.qacover.TestExecute.setUp(TestExecute.java:29)
...
Caused by: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12519, TNS:no appropriate service handler found
  (CONNECTION_ID=C/JtIjguQ8yLLqJwvPKz5g==)
	at oracle.jdbc.driver.T4CConnection.handleLogonNetException(T4CConnection.java:895)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:700)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1048)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:90)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:733)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:649)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at test4giis.qacoverapp.ConnectionFactory.getNativeConnection(ConnectionFactory.java:73)
	at test4giis.qacoverapp.AppBase.executeUpdateNative(AppBase.java:54)
	... 33 more
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12519, TNS:no appropriate service handler found
  (CONNECTION_ID=C/JtIjguQ8yLLqJwvPKz5g==)
	at oracle.net.ns.NSProtocolNIO.createRefusePacketException(NSProtocolNIO.java:833)
	at oracle.net.ns.NSProtocolNIO.handleConnectPacketResponse(NSProtocolNIO.java:405)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:[216](https://github.com/giis-uniovi/qacover/actions/runs/6987984114/job/19169156374#step:9:217))
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:355)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:2467)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:659)
	... 41 more
```

**Comment by javiertuya** [comment]
It seems to be fixed after migrating oracle to 21.3.0 cbec5fe
